(function($) {
    $(document).ready(function() {
	
	$('#OhNoPlotIsMoving').scianimator({
	    'images': ['images/OhNoPlotIsMoving1.png', 'images/OhNoPlotIsMoving2.png', 'images/OhNoPlotIsMoving3.png', 'images/OhNoPlotIsMoving4.png', 'images/OhNoPlotIsMoving5.png', 'images/OhNoPlotIsMoving6.png', 'images/OhNoPlotIsMoving7.png', 'images/OhNoPlotIsMoving8.png', 'images/OhNoPlotIsMoving9.png', 'images/OhNoPlotIsMoving10.png', 'images/OhNoPlotIsMoving11.png', 'images/OhNoPlotIsMoving12.png', 'images/OhNoPlotIsMoving13.png', 'images/OhNoPlotIsMoving14.png', 'images/OhNoPlotIsMoving15.png', 'images/OhNoPlotIsMoving16.png', 'images/OhNoPlotIsMoving17.png', 'images/OhNoPlotIsMoving18.png', 'images/OhNoPlotIsMoving19.png', 'images/OhNoPlotIsMoving20.png', 'images/OhNoPlotIsMoving21.png', 'images/OhNoPlotIsMoving22.png', 'images/OhNoPlotIsMoving23.png', 'images/OhNoPlotIsMoving24.png', 'images/OhNoPlotIsMoving25.png', 'images/OhNoPlotIsMoving26.png', 'images/OhNoPlotIsMoving27.png', 'images/OhNoPlotIsMoving28.png', 'images/OhNoPlotIsMoving29.png', 'images/OhNoPlotIsMoving30.png', 'images/OhNoPlotIsMoving31.png', 'images/OhNoPlotIsMoving32.png', 'images/OhNoPlotIsMoving33.png', 'images/OhNoPlotIsMoving34.png', 'images/OhNoPlotIsMoving35.png', 'images/OhNoPlotIsMoving36.png', 'images/OhNoPlotIsMoving37.png', 'images/OhNoPlotIsMoving38.png', 'images/OhNoPlotIsMoving39.png', 'images/OhNoPlotIsMoving40.png', 'images/OhNoPlotIsMoving41.png', 'images/OhNoPlotIsMoving42.png', 'images/OhNoPlotIsMoving43.png', 'images/OhNoPlotIsMoving44.png', 'images/OhNoPlotIsMoving45.png', 'images/OhNoPlotIsMoving46.png', 'images/OhNoPlotIsMoving47.png', 'images/OhNoPlotIsMoving48.png', 'images/OhNoPlotIsMoving49.png', 'images/OhNoPlotIsMoving50.png', 'images/OhNoPlotIsMoving51.png', 'images/OhNoPlotIsMoving52.png', 'images/OhNoPlotIsMoving53.png', 'images/OhNoPlotIsMoving54.png', 'images/OhNoPlotIsMoving55.png', 'images/OhNoPlotIsMoving56.png', 'images/OhNoPlotIsMoving57.png', 'images/OhNoPlotIsMoving58.png', 'images/OhNoPlotIsMoving59.png', 'images/OhNoPlotIsMoving60.png', 'images/OhNoPlotIsMoving61.png', 'images/OhNoPlotIsMoving62.png', 'images/OhNoPlotIsMoving63.png', 'images/OhNoPlotIsMoving64.png', 'images/OhNoPlotIsMoving65.png', 'images/OhNoPlotIsMoving66.png', 'images/OhNoPlotIsMoving67.png', 'images/OhNoPlotIsMoving68.png', 'images/OhNoPlotIsMoving69.png', 'images/OhNoPlotIsMoving70.png', 'images/OhNoPlotIsMoving71.png', 'images/OhNoPlotIsMoving72.png', 'images/OhNoPlotIsMoving73.png', 'images/OhNoPlotIsMoving74.png', 'images/OhNoPlotIsMoving75.png', 'images/OhNoPlotIsMoving76.png'],
	    'width': 480,
	    'delay': 20,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
	$('#OhNoPlotIsMoving').scianimator('play');
    });
})(jQuery);
