(function($) {
    $(document).ready(function() {
	
	$('#ChrisDemo').scianimator({
	    'images': ['images/ChrisDemo1.png', 'images/ChrisDemo2.png', 'images/ChrisDemo3.png', 'images/ChrisDemo4.png', 'images/ChrisDemo5.png', 'images/ChrisDemo6.png', 'images/ChrisDemo7.png', 'images/ChrisDemo8.png', 'images/ChrisDemo9.png', 'images/ChrisDemo10.png', 'images/ChrisDemo11.png', 'images/ChrisDemo12.png', 'images/ChrisDemo13.png', 'images/ChrisDemo14.png', 'images/ChrisDemo15.png', 'images/ChrisDemo16.png', 'images/ChrisDemo17.png', 'images/ChrisDemo18.png', 'images/ChrisDemo19.png', 'images/ChrisDemo20.png', 'images/ChrisDemo21.png', 'images/ChrisDemo22.png', 'images/ChrisDemo23.png', 'images/ChrisDemo24.png', 'images/ChrisDemo25.png', 'images/ChrisDemo26.png', 'images/ChrisDemo27.png', 'images/ChrisDemo28.png', 'images/ChrisDemo29.png', 'images/ChrisDemo30.png', 'images/ChrisDemo31.png', 'images/ChrisDemo32.png', 'images/ChrisDemo33.png', 'images/ChrisDemo34.png', 'images/ChrisDemo35.png', 'images/ChrisDemo36.png', 'images/ChrisDemo37.png', 'images/ChrisDemo38.png', 'images/ChrisDemo39.png', 'images/ChrisDemo40.png', 'images/ChrisDemo41.png', 'images/ChrisDemo42.png', 'images/ChrisDemo43.png', 'images/ChrisDemo44.png', 'images/ChrisDemo45.png', 'images/ChrisDemo46.png', 'images/ChrisDemo47.png', 'images/ChrisDemo48.png', 'images/ChrisDemo49.png', 'images/ChrisDemo50.png', 'images/ChrisDemo51.png', 'images/ChrisDemo52.png', 'images/ChrisDemo53.png', 'images/ChrisDemo54.png', 'images/ChrisDemo55.png', 'images/ChrisDemo56.png', 'images/ChrisDemo57.png', 'images/ChrisDemo58.png', 'images/ChrisDemo59.png', 'images/ChrisDemo60.png', 'images/ChrisDemo61.png', 'images/ChrisDemo62.png', 'images/ChrisDemo63.png', 'images/ChrisDemo64.png', 'images/ChrisDemo65.png', 'images/ChrisDemo66.png', 'images/ChrisDemo67.png', 'images/ChrisDemo68.png', 'images/ChrisDemo69.png', 'images/ChrisDemo70.png', 'images/ChrisDemo71.png', 'images/ChrisDemo72.png', 'images/ChrisDemo73.png', 'images/ChrisDemo74.png', 'images/ChrisDemo75.png', 'images/ChrisDemo76.png', 'images/ChrisDemo77.png', 'images/ChrisDemo78.png', 'images/ChrisDemo79.png', 'images/ChrisDemo80.png', 'images/ChrisDemo81.png', 'images/ChrisDemo82.png', 'images/ChrisDemo83.png', 'images/ChrisDemo84.png', 'images/ChrisDemo85.png', 'images/ChrisDemo86.png', 'images/ChrisDemo87.png', 'images/ChrisDemo88.png', 'images/ChrisDemo89.png', 'images/ChrisDemo90.png', 'images/ChrisDemo91.png', 'images/ChrisDemo92.png', 'images/ChrisDemo93.png', 'images/ChrisDemo94.png', 'images/ChrisDemo95.png', 'images/ChrisDemo96.png', 'images/ChrisDemo97.png', 'images/ChrisDemo98.png', 'images/ChrisDemo99.png', 'images/ChrisDemo100.png', 'images/ChrisDemo101.png', 'images/ChrisDemo102.png', 'images/ChrisDemo103.png', 'images/ChrisDemo104.png', 'images/ChrisDemo105.png', 'images/ChrisDemo106.png', 'images/ChrisDemo107.png', 'images/ChrisDemo108.png', 'images/ChrisDemo109.png', 'images/ChrisDemo110.png', 'images/ChrisDemo111.png', 'images/ChrisDemo112.png', 'images/ChrisDemo113.png'],
	    'width': 480,
	    'delay': 50,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
	$('#ChrisDemo').scianimator('play');
    });
})(jQuery);
